apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-sql-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-sql-injection
  template:
    metadata:
      labels:
        app: client-sql-injection
    spec:
      containers:
        - name: client-sql-injection
          image: ghcr.io/kube-hack/sql-injection:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: creds-db-sql-injection

---

apiVersion: v1
kind: Service
metadata:
  name: client-sql-injection
  labels:
    app: client-sql-injection
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 8080
  selector:
    app: client-sql-injection