apiVersion: v1
kind: ConfigMap
metadata:
  name: creds-db-sql-injection
  labels:
    app: creds-db-sql-injection
data:
  POSTGRES_USER: "{{ .Values.postgres.user }}"
  POSTGRES_PASSWORD: "{{ .Values.postgres.password }}"
  POSTGRES_URL: "postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@{{ .Values.postgres.host }}/{{ .Values.postgres.database }}?sslmode=disable"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-db-sql-injection
data:
  schema.sql: {{ .Files.Get "files/schema.sql" | indent 4 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-sql-injection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-sql-injection
  template:
    metadata:
      labels:
        app: db-sql-injection
    spec:
      containers:
        - name: db-sql-injection
          image: postgres
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: creds-db-sql-injection
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/
              name: schema-volume
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      volumes:
        - name: schema-volume
          configMap:
            name: schema-db-sql-injection

---

apiVersion: v1
kind: Service
metadata:
  name: db-sql-injection
  labels:
    app: db-sql-injection
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db-sql-injection